# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='menu',
        ),
    ]
