# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='operations',
        ),
    ]
