# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_management',
            field=models.SmallIntegerField(default=0, verbose_name='是否是主管人'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organization.Organization'),
        ),
    ]
